

services:
  app:
    build: .
    ports:
      - "3000:3000"
    # user: "1001:101"
    environment:
      NODE_ENV: production
      DOCKER_HOST: "unix:///var/run/docker.sock"
      OLLAMA_HOST: http://ollama:11434
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - ollama
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama 
    # deploy:
    #   resources:
    #     limits:
    #       memory: 8g