

services:
  carbon-tunnel:
    image: alpine:3.20
    restart: unless-stopped
    secrets:
      - tunnel_key
    # command: >
    #   sh -c "apk update && apk add --no-cache openssh-client curl autossh &&
    #          mkdir -p /root/.ssh &&
    #          chmod 700 /root/.ssh &&
    #          cp /run/secrets/tunnel_key /root/.ssh/id_rsa &&
    #          chmod 600 /root/.ssh/id_rsa &&
    #          ssh -o StrictHostKeyChecking=no -N -L 0.0.0.0:11434:localhost:11572 enzo@gx13.cse.unsw.edu.au"
    command: >
      sh -c 'apk update && apk add --no-cache openssh-client curl autossh &&
             mkdir -p /root/.ssh &&
             chmod 700 /root/.ssh &&
             cp /run/secrets/tunnel_key /root/.ssh/id_rsa &&
             chmod 600 /root/.ssh/id_rsa &&
             autossh -M 0  \
             -o ServerAliveInterval=30 -o ServerAliveCountMax=3 \
             -o ExitOnForwardFailure=yes \
             -o StrictHostKeyChecking=no \
             -N -L 0.0.0.0:11434:localhost:11572 enzo@gx13.cse.unsw.edu.au'
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    # volumes:
    #   - ./ssh:/root/.ssh:ro
  carbon-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DOCKER_HOST: "unix:///var/run/docker.sock"
      DCC_HELP_MODEL: "hf.co/Project-Carbon/Gemma3N-E4B-DCCHelp-gguf:BF16"
      OLLAMA_HOST: "http://carbon-tunnel:11434"
    volumes:
      # - /var/run/docker.sock:/var/run/docker.sock
      - /run/user/1000/docker.sock:/var/run/docker.sock
    depends_on: [carbon-tunnel]
      # carbon-tunnel:
        # condition: service_healthy
secrets:
  tunnel_key:
    file: ./ssh/id_ed25519