services:
  carbon-frontend:
    build: ./src/frontend/.
    working_dir: /app
    # restart: always
    ports:
      - 4200:4200
    environment:
      - NODE_ENV=development
      - PORT=4200
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - carbon-backend
  carbon-backend:
    build: ./src/backend/.
    working_dir: /usr/src/app
    # restart: always
    volumes:
      - ./src/backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - FRONTEND_URL=http://localhost
      - PORT=3000
    command: sh entry.sh
    # ports:
        # - 5555:5555
        # - 3000:3000
  carbon-nginx:
    image: nginx:latest
    # restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - carbon-frontend
      - carbon-backend
  # May need separate ollama service.