#!/bin/bash

PATH=/bin:/usr/bin:"$PATH"
what=$(basename "$0"|cut -d- -f1)
saved_json="${XDG_CACHE_HOME-$HOME/.cache}/$what.json"

if test ! -s "$saved_json" 
then
    echo "$0: nothing recorded to explain" 1>&2
    exit 1
fi

exec /opt/dcc-help/lib/query.py <"$saved_json"
